-- Drop the existing security definer view
DROP VIEW IF EXISTS public.careers_open_roles;

-- Recreate the view with the same data but without SECURITY DEFINER
-- (uses SECURITY INVOKER by default, which is more secure)
CREATE VIEW public.careers_open_roles AS
SELECT slug, title, team, department, location, onsite_requirement, employment, seniority, 
       salary_min, salary_max, currency, tags, brief
FROM (
  VALUES 
    ('ai-solutions-architect'::text,'AI Solutions Architect'::text,'AI & Machine Learning'::text,'Technology & Innovation'::text,'Houston, TX or Remote — US'::text,'Remote-first'::text,'full_time'::text,'senior'::text,165000,215000,'USD'::text,ARRAY['AI'::text, 'LLM'::text, 'RAG'::text, 'Consulting'::text],'Lead design and delivery of intelligent automation & GenAI solutions.'::text),
    ('senior-fullstack-supabase-react'::text,'Senior Full-Stack Engineer (Supabase/React)'::text,'Web & App Development'::text,'Technology & Innovation'::text,'SLC, UT or Remote — US'::text,'Remote-friendly'::text,'full_time'::text,'senior'::text,140000,190000,'USD'::text,ARRAY['React'::text, 'Next.js'::text, 'Supabase'::text, 'Cloudflare'::text],'Build scalable apps with Next.js, Supabase, Cloudflare Workers.'::text),
    ('cloud-engineer-gcp-aws'::text,'Cloud Engineer (GCP/AWS)'::text,'Cloud Services'::text,'Technology & Innovation'::text,'Houston, TX or Remote — US'::text,'Hybrid optional'::text,'full_time'::text,'mid'::text,125000,165000,'USD'::text,ARRAY['GCP'::text, 'AWS'::text, 'Terraform'::text],'Own secure, scalable cloud infra, IaC, CI/CD, observability.'::text),
    ('cybersecurity-engineer-soc2-automation'::text,'Cybersecurity Engineer (SOC2/Automation)'::text,'Cybersecurity'::text,'Technology & Innovation'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,120000,160000,'USD'::text,ARRAY['SOC2'::text, 'Automation'::text, 'SIEM'::text],'Security automation, SOC2 controls, incident response.'::text),
    ('data-analyst-product-marketing'::text,'Data Analyst (Product & Marketing)'::text,'Data Analytics'::text,'Technology & Innovation'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,90000,125000,'USD'::text,ARRAY['Analytics'::text, 'GA4'::text, 'Looker Studio'::text],'Insights, dashboards, AB testing across product & marketing.'::text),
    ('mobile-app-developer'::text,'Mobile App Developer (iOS/Android)'::text,'App Development'::text,'Technology & Innovation'::text,'SLC, UT or Remote — US'::text,'Remote-friendly'::text,'full_time'::text,'mid'::text,115000,150000,'USD'::text,ARRAY['React Native'::text, 'Flutter'::text, 'Supabase'::text],'Build high-quality RN/Flutter apps; payments, auth, push.'::text),
    ('ppc-lead-google-meta'::text,'PPC Lead (Google & Meta)'::text,'PPC & Paid Media'::text,'Marketing & Growth'::text,'Houston, TX or Remote — US'::text,'Hybrid optional'::text,'full_time'::text,'senior'::text,110000,145000,'USD'::text,ARRAY['Google Ads'::text, 'Meta Ads'::text, 'PPC'::text],'Own paid acquisition strategy, testing, and reporting.'::text),
    ('seo-strategist'::text,'SEO Strategist (Technical & Content)'::text,'SEO & Organic Growth'::text,'Marketing & Growth'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,90000,120000,'USD'::text,ARRAY['Technical SEO'::text, 'Local SEO'::text, 'Content'::text],'Technical SEO + content strategy for SaaS, Home Services, Healthcare.'::text),
    ('social-media-manager'::text,'Social Media Manager (B2B/B2C)'::text,'Social Media'::text,'Marketing & Growth'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,70000,95000,'USD'::text,ARRAY['Social'::text, 'UGC'::text, 'Short-form'::text],'Calendars, UGC, analytics; channel-specific strategies.'::text),
    ('marketing-analyst-attribution'::text,'Marketing Analyst (Attribution/ROAS)'::text,'Analytics'::text,'Marketing & Growth'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,95000,125000,'USD'::text,ARRAY['Attribution'::text, 'ROAS'::text, 'Analytics'::text],'Build MMM/attribution; unify GA4, ad platforms, CRM.'::text),
    ('senior-video-producer'::text,'Senior Video Producer (Ads & Brand)'::text,'Video Production'::text,'Creative Media Studio'::text,'Houston, TX (preferred) or SLC'::text,'Onsite/Hybrid'::text,'full_time'::text,'senior'::text,105000,140000,'USD'::text,ARRAY['Video'::text, 'Ads'::text, 'Brand'::text],'Lead production end-to-end for ads & brand films.'::text),
    ('video-editor-motion-designer'::text,'Video Editor / Motion Designer'::text,'Post-Production & Animation'::text,'Creative Media Studio'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,80000,105000,'USD'::text,ARRAY['Editing'::text, 'Motion'::text, 'VFX'::text],'Edit shorts/case studies; motion graphics & light VFX.'::text),
    ('3d-generalist'::text,'3D Generalist (Product & VFX)'::text,'3D & Visual Effects'::text,'Creative Media Studio'::text,'Remote — US'::text,'Remote-first'::text,'contract'::text,'senior'::text,60000,90000,'USD'::text,ARRAY['3D'::text, 'Renders'::text, 'VFX'::text],'Photoreal product renders and light VFX for ads/web.'::text),
    ('photographer-product-brand'::text,'Photographer (Product & Brand)'::text,'Photography'::text,'Creative Media Studio'::text,'Houston, TX or SLC'::text,'Onsite/Hybrid'::text,'contract'::text,'mid'::text,50000,90000,'USD'::text,ARRAY['Studio'::text, 'Product'::text, 'Brand'::text],'Product & lifestyle shoots; create asset libraries.'::text),
    ('audio-producer-sound-designer'::text,'Audio Producer / Sound Designer'::text,'Audio Production'::text,'Creative Media Studio'::text,'Remote — US'::text,'Remote-first'::text,'part_time'::text,'mid'::text,40000,65000,'USD'::text,ARRAY['Audio'::text, 'VO'::text, 'Mix'::text],'Sound design, VO, mix for ads/brand videos.'::text),
    ('account-director'::text,'Account Director (Enterprise & Growth)'::text,'Client Success'::text,'Sales & Client Success'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'director'::text,135000,180000,'USD'::text,ARRAY['Account Management'::text, 'Enterprise'::text],'Own exec relationships, renewals, upsell; $1–3M book.'::text),
    ('sales-executive-solutions'::text,'Sales Executive (Solutions Consultant)'::text,'Sales'::text,'Sales & Client Success'::text,'Houston, TX or Remote — US'::text,'Hybrid optional'::text,'full_time'::text,'mid'::text,90000,120000,'USD'::text,ARRAY['Sales'::text, 'Solutions'::text],'Drive new business across AI, web, PPC/SEO, creative.'::text),
    ('project-manager-agile'::text,'Project Manager (Agile/Client Services)'::text,'Operations'::text,'Operations & Finance'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,95000,125000,'USD'::text,ARRAY['PM'::text, 'Agile'::text, 'Delivery'::text],'Plan & deliver multi-disciplinary projects on time/budget.'::text),
    ('revops-analyst'::text,'Finance & RevOps Analyst'::text,'Operations'::text,'Operations & Finance'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,90000,120000,'USD'::text,ARRAY['RevOps'::text, 'Finance'::text, 'Analytics'::text],'Billing ops, margin tracking, revenue analytics.'::text),
    ('talent-partner'::text,'Talent Partner (Technical & Creative)'::text,'People'::text,'People & Talent'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,80000,105000,'USD'::text,ARRAY['Recruiting'::text, 'ATS'::text, 'Brand'::text],'Source/close technical, marketing, creative talent.'::text),
    ('solutions-designer-automation'::text,'Solutions Designer (Automation & Integrations)'::text,'Automation & Integrations'::text,'Technology & Innovation'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,105000,135000,'USD'::text,ARRAY['Automation'::text, 'Integrations'::text, 'API'::text],'Design workflows & integrations across CRMs/ERPs/APIs.'::text),
    ('digital-strategist'::text,'Digital Strategist (Transformation)'::text,'Digital Strategy Consulting'::text,'Technology & Innovation'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'senior'::text,125000,165000,'USD'::text,ARRAY['Strategy'::text, 'Roadmapping'::text, 'Governance'::text],'Discovery, roadmaps, governance; 90-day plans.'::text),
    ('web-developer-nextjs-seo'::text,'Web Developer (Next.js/SEO-Ready)'::text,'Website Development'::text,'Technology & Innovation'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,100000,135000,'USD'::text,ARRAY['Next.js'::text, 'SEO'::text, 'Headless CMS'::text],'Build fast, SEO-ready marketing sites & headless storefronts.'::text),
    ('creative-director-integrated'::text,'Creative Director (Integrated)'::text,'Creative'::text,'Creative Media Studio'::text,'Houston, TX or Remote — US'::text,'Hybrid optional'::text,'full_time'::text,'director'::text,140000,185000,'USD'::text,ARRAY['Creative'::text, 'Brand'::text, 'Campaigns'::text],'Own creative across campaigns, web, and video.'::text),
    ('copywriter-performance-brand'::text,'Copywriter (Performance & Brand)'::text,'Content'::text,'Marketing & Growth'::text,'Remote — US'::text,'Remote-first'::text,'full_time'::text,'mid'::text,80000,105000,'USD'::text,ARRAY['Copy'::text, 'Direct Response'::text, 'Scripts'::text],'Write landing pages, ads, scripts, and case studies.'::text)
) AS r(slug, title, team, department, location, onsite_requirement, employment, seniority, salary_min, salary_max, currency, tags, brief);

-- Note: Views are readable by default. Only Supabase admins can modify the view definition itself.
-- Since this is a static view with hardcoded data, there's no underlying table to restrict.