// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Load from Vite env (do not hardcode!)
// Strip quotes if present (handles quoted env values)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL!.replace(/^["'](.*)["']$/, '$1');
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY!.replace(/^["'](.*)["']$/, '$1');

// Single client export using the anon key
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
